### ISSUE TITLE
Class gvasilopulos\console\controllers\RbacfeController does not exist

### ISSUE THREAD

**Issue by zieglar** [gvasilopulos/yii2-rbacfe#2]
hi @gvasilopulos ,
my console/config/main.php contain
'controllerMap' => [
     'rbacfe' => 'gvasilopulos\console\controllers\RbacfeController'
],

but when I run `php yii`, exception is

Exception 'ReflectionException' with message 'Class gvasilopulos\console\controllers\RbacfeController does not exist'

in /Users/zieglar/Code/DrNCD/vendor/yiisoft/yii2/di/Container.php:424

can you hellp me?

**Comment by gvasilopulos** [comment]
Hello and sorry for the delay
Did you add the classmap ?
Yii::$classMap['gvasilopulos\console\controllers\RbacfeController'] = '@vendor/gvasilopulos/yii2-rbacfe/console/controllers/RbacfeController.php'; 
somehow autoload is not perfect in yii console or I haven't understood how to make it work.
the solution I found is to add the classmap statement.
this is my console/config/main.php for reference 

`<?php
$params = array_merge(
    require(__DIR__ . '/../../common/config/params.php'),
    require(__DIR__ . '/../../common/config/params-local.php'),
    require(__DIR__ . '/params.php'),
    require(__DIR__ . '/params-local.php')
);
Yii::$classMap['gvasilopulos\console\controllers\RbacfeController'] = '@vendor/gvasilopulos/yii2-rbacfe/console/controllers/RbacfeController.php';

return [
    'id' => 'app-console',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'controllerNamespace' => 'console\controllers',
    'components' => [
        'log' => [
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
    ],
    //'aliases' => [
    //    '@gvasrbac' => 'vendor/gvasilopulos/yii2-rbacfe',
        
    //    ],
    'controllerMap' => [
     'rbacfe' => 'gvasilopulos\console\controllers\RbacfeController'
     ],
    'params' => $params,
];
`

**Comment by zieglar** [comment]
ok, I see

it's work, thank you :)

please add to Readme.

**Comment by gvasilopulos** [comment]
nice
